export const BATH_PATH='http://localhost:8080/basic-webapp'
export const LOGIN_PATH='/local/logincheck'
export const MODIFY_PATH='/local/logincheck'
export const SHOP_LIST_PATH='/shopadmin/getshoplist'
export const KAPTCHA_PATH='/local/vuekaptcha'
