// 根据环境变量判断使用哪个后端地址
// 开发环境: http://localhost:8080/basic-webapp
// 生产环境(Docker): /api
export const BATH_PATH = import.meta.env.PROD ? '/api' : 'http://localhost:8080'
export const IMAGE_PATH = import.meta.env.PROD ? '/api/frontend/' : 'http://localhost:8080/frontend/'
export const LOGIN_PATH='/local/logincheckend'
export const MODIFY_PASSWORD_PATH='/local/changelocalpwdend'
export const SHOP_LIST_PATH='/shopadmin/getshoplistend'
export const ADD_SHOP_PATH='/shopadmin/registershopend'
export const KAPTCHA_PATH='/local/vuekaptcha'
export const SHOP_INFO_PATH='/shopadmin/getshopinitinfo'
export const SHOP_PATH='/shopadmin/getshopbyid'
export const MODITY_SHOP_PATH='/shopadmin/modifyshopInfo'
export const CATEGORY_PATH='/shopadmin/getproductcategorylistend'
export const ADD_CATEGORY_PATH='/shopadmin/addproductcategorysend'
export const REMOVE_CATEGORY_PATH='/shopadmin/removeproductcategoryend'
export const PRODUCT_LIST_PATH='/shopadmin/getproductlistbyshopend'
export const PRODUCT_PATH='/shopadmin/getproductbyid'
export const PRODUCT_MODIFY_PATH='/shopadmin/modifyproductend'
export const PRODUCT_DETAIL_INFO_PATH='/frontend/listproductdetailpageinfo'
export const PRODUCT_ADD_PATH='/shopadmin/addproductend'