export default [
  "models/_AreaType.ts",
  "models/_PersonType.ts",
  "models/_ShopCategory.ts",
  "models/_ShopDetailResult.ts",
  "models/_ShopInitInfoResult.ts",
  "models/_ShopListResult.ts",
  "models/_ShopType.ts",
  "models/AreaTye.ts",
  "models/PersonType.ts",
  "models/ShopCategory.ts",
  "models/ShopListResult.ts",
  "models/ShopDetailResults.ts",
  "models/ShopInitInfoResult.ts",
  "models/ShopType.ts",
  "models/ShopList.ts",  
  ];